# Generated by Django 4.0.4 on 2022-05-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
