# Generated by Django 4.0.4 on 2022-05-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_alter_fund_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='aum',
            field=models.IntegerField(blank=True, null=True, verbose_name='AUM (USD)'),
        ),
    ]
